services:
  ejabberd:
    build: ./ejabberd
    container_name: ejabberd
    ports:
      - "5222:5222"
      - "5223:5223"
      - "5280:5280"
    volumes:
      - ./ejabberd/certs:/opt/ejabberd/certs
    networks:
      - node-ejabberd-network

  app:
    build: ./
    container_name: app
    depends_on:
      - ejabberd
    volumes:
      - app_data:/usr/src/app/data
    networks:
      - node-ejabberd-network

volumes:
  app_data:

networks:
  node-ejabberd-network:
    driver: bridge
